### ISSUE TITLE
bug in the deep learning tutorial

### ISSUE THREAD

**Issue by jjvaldes** [ThomasMBury/ewstools#437]
There is a bug in the Deep learning classifiers for bifurcation prediction (tutorial_deep_learning.ipynb).
In particular, when plotting the ensemble average. The statement
ts_may.make_plotly(ens_avg=True)

makes the program crash.
The bug is in the function 'make_plotly', specifically with the statement:
df_plot = ts.dl_preds.groupby(['time']).mean().reset_index()

The bug is caused by the presence of column 'classifier' within the 'ts.dl_preds' frame.

A quick fix can be made by replacing the above statement with the following two:
            df      = ts.dl_preds.drop(['classifier'], axis=1) # JJV
            df_plot = df.groupby(['time']).mean().reset_index()  # JJV
I verified that the redefined function 'make_plotly' with the fix works flawlessly.
Thank you for developing the (ewstools) package. It is excellent and it has been very useful in my research.
I have some suggestions on how to further extend the package, which I would like to discuss with the ewstools development team.

Julio Valdes
National Research Council Canada
julio.valdes@nrc-cnrc.gc.ca

**Comment by ThomasMBury** [comment]
Thanks @jjvaldes. I've made your suggested change. Feel free to submit a pull request in the future, that way your contributions will get tracked by Github.

I'm glad to hear that you are finding the package useful. So far, it's just me on the developer team. You can send me an email at thomas.bury@mcgill.ca if you want to discuss potential developments.

Thomas Bury
